# Generated by Django 4.2.16 on 2026-06-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_commissionrule_max_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrule',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], unique=True, verbose_name='Dia da Semana'),
        ),
    ]
