# Generated by Django 4.2.16 on 2026-06-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_commissionrule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionrule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da Semana'),
        ),
    ]
